### ISSUE TITLE
Extensions not working since 1.42.1 update

### ISSUE THREAD

**Issue by Quiwy** [VSCodium/vscodium#337]
**Describe the bug**
Extensions are not working anymore

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.
I don't use VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
Update to 1.42.1

**Expected behavior**
Extensions working.

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-14T10:21:44.789Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

```
 codium.cmd --list-extensions
Error: Le module sp├®cifi├® est introuvable.
\\?\C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar\spdlog\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\node_modules.asar\spdlog\index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at t.load (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:16:119)
    at e.load (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:586)
    at i (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:29:189)
    at Object.errorback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:29:313)
    at e.triggerErrorback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:955)
    at C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:13:659
    at ReadFileContext.callback (C:\Users\nicolas.caillet\AppData\Local\Programs\VSCodium\resources\app\out\vs\loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous5===' ]
}
bierner.emojisense
bierner.markdown-checkbox
bierner.markdown-emoji
bierner.markdown-footnotes
bierner.markdown-image-size
bierner.markdown-preview-github-styles
CoenraadS.bracket-pair-colorizer-2
eamodio.gitlens
EditorConfig.EditorConfig
eriklynd.json-tools
fatihacet.gitlab-workflow
GrapeCity.gc-excelviewer
HackMD.vscode-hackmd
henriiik.docker-linter
hnw.vscode-auto-open-markdown-preview
jebbs.plantuml
lacroixdavid1.vscode-format-context-menu
Mebrahtom.plantumlpreviewer
mhutchie.git-graph
mohsen1.prettify-json
ms-azuretools.vscode-docker
ms-python.python
ms-vscode.cpptools
ronzhong.cppcheckcmd
shd101wyy.markdown-preview-enhanced
SirTori.indenticator
yzane.markdown-pdf
yzhang.markdown-all-in-one
ZainChen.json
```

**Comment by stripedpajamas** [comment]
Could this be related to #331 ? It was mentioned in that thread that extensions aren't working as a result.

**Comment by sevkin** [comment]
confim **ms-azuretools.vscode-docker** continues not to work on vscodium 1.46.1; ubuntu 18.04 with mesage
```
[exthost] [error] Activating extension ms-azuretools.vscode-docker failed due to an error:
[exthost] [error] Error: Cannot find module 'getCoreNodeModule'
```

**Comment by MuhmdRaouf** [comment]
I can confirm the same, I can't even find the extensions to install them

**Comment by renestalder** [comment]
I can also confirm.

* Extension search doesn't reveal any results
* The `ext` command doesn't work to install extensions, like when you copy/paste it from the Marketplace.
* Recommended extensions as defined in the project workspace via `.vscode` folder show an error that the extension couldn't be found in the marketplace.

**Comment by renestalder** [comment]
Alright, after going through a couple of tickets, I guess that might just be the expected behaviour in my case based on a change that was introduced, that replaces Microsoft's Marketplace with a different want.

https://github.com/VSCodium/vscodium/issues/418#issuecomment-643664182

**Comment by jankeromnes** [comment]
Update: We've just published an updated version of `ms-azuretools.vscode-docker` to OpenVSX: https://open-vsx.org/extension/ms-azuretools/vscode-docker

This new version of the extension was also compiled with the extra command `npm run package` prior to publishing, which should hopefully produce a working extension (we'll now delete the likely-broken version `1.0.0` from OpenVSX).

Please kindly confirm that the newly uploaded Docker extension works as intended now.

**Comment by hashtaq** [comment]
I also have this problem. Since the update, VSCodium can't find certain extensions like kite copilot. The extension is just not found. Can somebody help?

**Comment by jankeromnes** [comment]
@hashtaq Please note that VSCodium now sources its extensions from https://open-vsx.org (the open-source vendor-neutral VSCode extensions registry) because Microsoft's own marketplace is closed-source and has a very restrictive proprietary license.

And, while most common/popular extensions are already available on OpenVSX, it's still very new and a few extensions may be missing. If that's the case, you can:

1. politely ask the extension maintainers to consider publishing to OpenVSX (they only need to run one command: `npx ovsx publish`, without installing anything), or

2. add it to OpenVSX's own automated publishing CI for open-source extensions: https://github.com/open-vsx/publish-extensions

Now, for Kite specifically, I'm not exactly sure what the problem is, but I've found these potentially relevant issues:

- https://github.com/kiteco/vscode-plugin/issues/298
- https://github.com/kiteco/issue-tracker/issues/224

**Comment by sevkin** [comment]
> Please kindly confirm that the newly uploaded Docker extension works as intended now.

docker extension now works

**Comment by hashtaq** [comment]
> @hashtaq Please note that VSCodium now sources its extensions from https://open-vsx.org (the open-source vendor-neutral vscode extensions registry) because Microsoft's own marketplace is closed-source and has a restrictive proprietary license.
> 
> And, while most common/popular extensions are already available on OpenVSX, it's still very new and a few extensions may be missing. If that's the case, you can:
> 
>     1. politely ask the extension maintainers to consider publishing to OpenVSX (they only need to run one command: `npx ovsx publish`, without installing anything), or
> 
>     2. add it to OpenVSX's own automated publishing CI for open-source extensions: https://github.com/open-vsx/publish-extensions
> 
> 
> Now, for Kite specifically, I'm not exactly sure what the problem is, but I've found these potentially relevant issues:
> 
>     * [kiteco/vscode-plugin#298](https://github.com/kiteco/vscode-plugin/issues/298)
> 
>     * [kiteco/issue-tracker#224](https://github.com/kiteco/issue-tracker/issues/224)

Thank you very much for your response. I will email the extension maintainers

**Comment by 21h** [comment]
returned "evil" back to codium, recipe here https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
